### ISSUE TITLE
Plugin in camel case ? 

### ISSUE THREAD

**Issue by maxired** [senecajs/generator-seneca-plugin#4]
Hi, 

Do we really want plugins to be named in camelcase ? 

I believe that all plugins are currently named in kebab-case. Looks like a big move

[Trello Card](https://trello.com/c/sHNjQaN4/70-generator-seneca-plugin-plugin-in-camel-case)

**Comment by mcdonnelldean** [comment]
Where is this? I think kebab-case is the standard alright.

**Comment by maxired** [comment]
https://github.com/senecajs/generator-seneca-plugin/blob/master/generators/app/index.js#l25

**Comment by geek** [comment]
Definitely should change that
