### ISSUE TITLE
new plugin with node 4 has minimal

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/generator-seneca-plugin#9]
I am considering enforcing node 4.0 has minimal for the new plugins by default.
(already the case for the generator itself with 5172df9)

@geek @mcdonnelldean, you agree?
If you think useful, I can consider an option. :)

**Comment by geek** [comment]
Not quite yet, we want to do this when we ship Seneca 2, which should be in March.

**Comment by AdrieanKhisbe** [comment]
okey dokey!
I'll add a pending tag then ;)

By the way, We should talk some time about the _“Road24”_ ;)
